### ISSUE TITLE
Spot cannot contain upper case characters (error "Long running operation failed")

### ISSUE THREAD

**Issue by giggio** [derekbekoe/vscode-spot#37]
I am getting this error when I try to create a spot with VSCode:

````
Unable to create spot: Error: Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.".
````

**Comment by derekbekoe** [comment]
Can you visit https://portal.azure.com and check what the error was in the deployment? You should see the list of deployments under the vscode-spot resource group.

e.g.:
<img width="903" alt="screen shot 2018-05-02 at 11 08 39 pm" src="https://user-images.githubusercontent.com/16448634/39561950-d0546a9e-4e5d-11e8-912e-99e76f9ce279.png">

**Comment by giggio** [comment]
Got it. It seems you cannot use UPPER CASE characters. Here is the message I got:

> The DNS name label 'Teste' in container group 'Teste' is invalid. It can contain only lowercase letters, numbers and hyphens. The first character must be a letter. The last character must be a letter or number. The value must be between 5 and 63 characters long.

I tried with only lower case characters and it worked. It would be nice to inform that on the tool, and avoid the failure.
